name: FantasyProtection
version: 1.0.1
author: Enrick3344
main: FantasyProtection\Main
api: [3.0.0-ALPHA7]

permission:
    fantasyprotection.break.bypass:
        default: op
    fantasyprotection.place.bypass:
        default: op
    fantasyprotection.drop.bypass:
        default: op
